"""Regenerate the notebook library cell (Cell 2) from src/ modules.

Inlines each src/*.py in dependency order, stripping intra-package imports. Writes
back to notebooks/kaggle_experiment.ipynb (Cell 2).
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
NOTEBOOK = ROOT / "notebooks" / "kaggle_experiment.ipynb"

FILES_IN_ORDER = [
    "config.py",
    "data.py",
    "features.py",
    "tokenization.py",
    "model.py",
    "features_head.py",
    "multitask.py",
    "train.py",
    "evaluate.py",
    "experiment.py",
]

INTRA_IMPORT_PATTERNS = [
    # Multi-line first ώστε να μην "φάει" η single-line μόνο την αρχή.
    re.compile(r"^from \.[\w_]+ import \([^)]*\)", re.MULTILINE),
    re.compile(r"^from \.[\w_]+ import .+$", re.MULTILINE),
    re.compile(r"^from \. import .+$", re.MULTILINE),
]


def strip_intra_imports(text: str) -> str:
    for pat in INTRA_IMPORT_PATTERNS:
        text = pat.sub("", text)
    return text


def build_library_cell() -> str:
    parts = [
        "# Cell 2 - Library (inlined src/) - auto-generated by scripts/build_library_cell.py",
        "# " + "=" * 60,
    ]
    for fname in FILES_IN_ORDER:
        p = SRC / fname
        if not p.exists():
            print(f"[warn] missing {p}, skipping")
            continue
        parts.append(f"# {'=' * 60}")
        parts.append(f"# src/{fname}")
        parts.append(f"# {'=' * 60}")
        body = p.read_text()
        body = strip_intra_imports(body).strip("\n") + "\n"
        parts.append(body)
    parts.append('print("library loaded ok")')
    return "\n".join(parts)


def main():
    nb = json.loads(NOTEBOOK.read_text())
    lib_cell = None
    for i, cell in enumerate(nb["cells"]):
        src = cell["source"] if isinstance(cell["source"], str) else "".join(cell["source"])
        if src.startswith("# Cell 2 - Library"):
            lib_cell = i
            break
    if lib_cell is None:
        raise RuntimeError("Could not locate library cell (expected header '# Cell 2 - Library').")

    new_text = build_library_cell()
    nb["cells"][lib_cell]["source"] = new_text.splitlines(keepends=True)
    nb["cells"][lib_cell]["outputs"] = []
    nb["cells"][lib_cell]["execution_count"] = None
    NOTEBOOK.write_text(json.dumps(nb, indent=1))
    print(f"Updated library cell at index {lib_cell} ({len(new_text.splitlines())} lines)")


if __name__ == "__main__":
    main()
