const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const root = path.resolve(__dirname, "..");
const sourceNb = path.join(root, "notebooks", "kaggle_experiment.ipynb");
const outDir = path.join(root, "notebooks");

function lines(text) {
  const arr = text.trim().split(/\r?\n/);
  return arr.map((line, i) => (i < arr.length - 1 ? line + "\n" : line));
}

function id() {
  return crypto.randomUUID();
}

function md(source) {
  return { cell_type: "markdown", id: id(), metadata: {}, source: lines(source) };
}

function code(source) {
  return {
    cell_type: "code",
    id: id(),
    metadata: {},
    execution_count: null,
    outputs: [],
    source: lines(source),
  };
}

const devNb = JSON.parse(fs.readFileSync(sourceNb, "utf8"));
function cellSource(cell) {
  return Array.isArray(cell.source) ? cell.source.join("") : (cell.source || "");
}
const installCell = cellSource(devNb.cells.find((c) => cellSource(c).includes("# Cell 1") && cellSource(c).includes("Install")));
let libraryCell = cellSource(devNb.cells.find((c) => cellSource(c).includes("# Cell 2") && cellSource(c).includes("Library")));

if (!installCell || !libraryCell) {
  throw new Error("Could not find install/library cells in notebooks/kaggle_experiment.ipynb");
}

libraryCell = libraryCell
  .replace("# Cell 2 - Library (inlined src/) - auto-generated by scripts/prepare_breakthrough_notebook.js", "# Cell 2 - Notebook library")
  .replaceAll("# src/config.py", "# Configuration")
  .replaceAll("# src/data.py", "# Data loading")
  .replaceAll("# src/features.py", "# Numeric and text features")
  .replaceAll("# src/evasion_stack.py", "# Evasion helper models")
  .replaceAll("# src/tokenization.py", "# Tokenization")
  .replaceAll("# src/model.py", "# Model wrappers")
  .replaceAll("# src/features_head.py", "# Feature-concat heads")
  .replaceAll("# src/multitask.py", "# Multi-task heads")
  .replaceAll("# src/train.py", "# Training loop")
  .replaceAll("# src/evaluate.py", "# Evaluation")
  .replaceAll("# src/experiment.py", "# Experiment runner");

const runSweepCell = `
# Run final configuration(s)
import gc
import torch

sweep_results = []
for cfg in sweep_configs:
    print("\\n" + "=" * 60)
    print("RUNNING:", cfg.run_id)
    print("=" * 60)
    history, val_logits, val_labels, test_df, tokenizer, model, device = run_experiment(cfg)
    best = max(history, key=lambda x: x["f1_macro"])
    sweep_results.append({
        "cfg": cfg,
        "run_id": cfg.run_id,
        "run_dir": str(Path(cfg.models_dir) / cfg.run_id),
        "history": history,
        "best_epoch": best["epoch"],
        "val_f1_macro": best["f1_macro"],
        "val_acc": best["accuracy"],
        "f1_CR": best["f1_per_class"][0],
        "f1_AMB": best["f1_per_class"][1],
        "f1_CNR": best["f1_per_class"][2],
    })
    model.cpu()
    del model, tokenizer
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

print("\\nAll final runs complete.")
`;

const resultsCell = `
# Results table
import pandas as pd

rows = []
for r in sweep_results:
    rows.append({
        "run_id": r["run_id"],
        "best_epoch": r["best_epoch"],
        "val_f1_macro": round(r["val_f1_macro"], 4),
        "val_acc": round(r["val_acc"], 4),
        "f1_CR": round(r["f1_CR"], 4),
        "f1_AMB": round(r["f1_AMB"], 4),
        "f1_CNR": round(r["f1_CNR"], 4),
    })
results_df = pd.DataFrame(rows).sort_values("val_f1_macro", ascending=False)
display(results_df)
print("Best:", results_df.iloc[0].to_dict())
`;

const confusionCell = `
# Confusion matrix for the best validation run
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from pathlib import Path

best_run = sorted(sweep_results, key=lambda r: r["val_f1_macro"], reverse=True)[0]
val_logits = np.load(Path(best_run["run_dir"]) / "val_preds.npy")
val_labels = np.load(Path(best_run["run_dir"]) / "val_labels.npy")
preds = val_logits.argmax(axis=1)
cm = confusion_matrix(val_labels, preds, labels=[0, 1, 2])
label_names = ["Clear Reply", "Ambivalent", "Clear Non-Reply"]

fig, ax = plt.subplots(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", xticklabels=label_names, yticklabels=label_names, cmap="Blues", ax=ax)
ax.set_xlabel("Predicted")
ax.set_ylabel("True")
ax.set_title(f"{best_run['run_id']}\\nval F1-macro={best_run['val_f1_macro']:.4f}")
plt.tight_layout()
plt.savefig("/kaggle/working/confusion_matrix.png", dpi=150)
plt.show()
print("cm:", cm.tolist())
`;

const singleSubmissionCell = (shortName) => `
# Generate Kaggle submission for the best single run
import gc
import pandas as pd
import numpy as np
import torch
from pathlib import Path
from torch.utils.data import DataLoader, SequentialSampler

best_run = sorted(sweep_results, key=lambda r: r["val_f1_macro"], reverse=True)[0]
cfg = best_run["cfg"]
run_dir = Path(best_run["run_dir"])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

reload_model, reload_tok = load_model_and_tokenizer(cfg.model_name, num_labels=NUM_LABELS)
reload_model.load_state_dict(torch.load(run_dir / "best_model.pt", map_location=device))
reload_model.to(device).eval()

_, test_df = load_clarity()
test_df_enc = test_df.copy()
test_df_enc["label_id"] = 0
test_df_enc = apply_text_transforms_for_config(test_df_enc, cfg)
test_ds = tokenize_pairs(test_df_enc, reload_tok, cfg.max_length, cfg.input_fmt)
test_loader = DataLoader(test_ds, batch_size=cfg.batch_size, sampler=SequentialSampler(test_ds))

all_logits = []
with torch.no_grad():
    for batch in test_loader:
        input_ids, attention_mask, _ = [b.to(device) for b in batch]
        out = reload_model(input_ids=input_ids, attention_mask=attention_mask)
        all_logits.append(out.logits.cpu().numpy())
test_logits = np.concatenate(all_logits, axis=0)
preds = test_logits.argmax(axis=1)

submission = pd.DataFrame({
    "Id": test_df["index"] if "index" in test_df.columns else range(len(test_df)),
    "Predicted": [ID2LABEL[int(p)] for p in preds],
})
submission.to_csv("/kaggle/working/submission_${shortName}.csv", index=False)
submission.to_csv("/kaggle/working/submission.csv", index=False)
print("Saved /kaggle/working/submission.csv")
print("Saved /kaggle/working/submission_${shortName}.csv")
display(submission.head())
print(submission["Predicted"].value_counts())

reload_model.cpu()
del reload_model, reload_tok
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
`;

const debertaSubmissionCell = `
# Generate Phase 18 DeBERTa multi-view ensemble submission
import gc
import shutil
import pandas as pd
import numpy as np
import torch
from pathlib import Path
from sklearn.metrics import f1_score
from torch.utils.data import DataLoader, SequentialSampler

label_names_map = {0: "Clear Reply", 1: "Ambivalent", 2: "Clear Non-Reply"}

def softmax_np(x, axis=-1):
    x = x - x.max(axis=axis, keepdims=True)
    e = np.exp(x)
    return e / e.sum(axis=axis, keepdims=True)

def load_run_logits_for_test(r):
    cfg = r["cfg"]
    run_dir = Path(r["run_dir"])
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    feature_stats = load_feature_stats(run_dir / "feature_stats.json")
    reload_model, reload_tok = load_feature_model_and_tokenizer(
        cfg.model_name,
        num_labels=NUM_LABELS,
        num_features=len(feature_stats["feature_names"]),
        feature_hidden=cfg.numeric_feature_hidden,
    )

    reload_model.load_state_dict(torch.load(run_dir / "best_model.pt", map_location=device))
    reload_model.to(device).eval()

    _, test_df = load_clarity()
    test_df_enc = test_df.copy()
    test_df_enc["label_id"] = 0
    test_df_enc = apply_text_transforms_for_config(test_df_enc, cfg)
    test_features = transform_numeric_features(test_df_enc, feature_stats)
    test_ds = tokenize_pairs_with_features(
        test_df_enc, reload_tok, cfg.max_length, cfg.input_fmt, test_features
    )
    test_loader = DataLoader(test_ds, batch_size=cfg.batch_size, sampler=SequentialSampler(test_ds))

    all_logits = []
    with torch.no_grad():
        for batch in test_loader:
            input_ids, attention_mask, _, features = [b.to(device) for b in batch]
            out = reload_model(input_ids=input_ids, attention_mask=attention_mask, features=features)
            all_logits.append(out.logits.cpu().numpy())
    test_logits = np.concatenate(all_logits, axis=0)

    reload_model.cpu()
    del reload_model, reload_tok
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return test_df, test_logits

def write_submission(name, test_df, preds):
    submission = pd.DataFrame({
        "Id": test_df["index"] if "index" in test_df.columns else range(len(test_df)),
        "Predicted": [label_names_map[int(p)] for p in preds],
    })
    path = f"/kaggle/working/{name}.csv"
    submission.to_csv(path, index=False)
    print(f"{name}.csv -> {path}")
    print(f"  Distribution: {dict(submission['Predicted'].value_counts())}")
    return path

all_runs = sorted(sweep_results, key=lambda r: r["val_f1_macro"], reverse=True)
val_labels_ref = np.load(Path(all_runs[0]["run_dir"]) / "val_labels.npy")

test_df_ref = None
val_probs = []
test_probs = []
for r in all_runs:
    val_logits = np.load(Path(r["run_dir"]) / "val_preds.npy")
    val_probs.append(softmax_np(val_logits))
    test_df_ref, test_logits = load_run_logits_for_test(r)
    test_probs.append(softmax_np(test_logits))
    write_submission("submission_single_" + r["run_id"].replace("/", "_"), test_df_ref, test_logits.argmax(axis=1))

equal_val = np.mean(val_probs, axis=0)
equal_test = np.mean(test_probs, axis=0)
equal_f1 = f1_score(val_labels_ref, equal_val.argmax(axis=1), average="macro", zero_division=0)
equal_path = write_submission("submission_equal_deberta_phase18", test_df_ref, equal_test.argmax(axis=1))
print(f"Equal ensemble val F1: {equal_f1:.4f}")

grid = np.linspace(0.0, 1.0, 21)
best = (-1.0, None)
for a in grid:
    for b in grid:
        c = 1.0 - a - b
        if c < -1e-9:
            continue
        weights = np.array([a, b, c], dtype=np.float32)
        ens = sum(w * p for w, p in zip(weights, val_probs))
        f1 = f1_score(val_labels_ref, ens.argmax(axis=1), average="macro", zero_division=0)
        if f1 > best[0]:
            best = (f1, weights)

best_f1, best_w = best
alpha_test = sum(w * p for w, p in zip(best_w, test_probs))
alpha_path = write_submission("submission_alpha_deberta_phase18", test_df_ref, alpha_test.argmax(axis=1))
print(f"Alpha ensemble val F1: {best_f1:.4f}, weights={best_w.tolist()}")

chosen = alpha_path if best_f1 >= equal_f1 else equal_path
shutil.copyfile(chosen, "/kaggle/working/submission.csv")
print(f"Default /kaggle/working/submission.csv copied from: {chosen}")
`;

const debertaPhase12SubmissionCell = `
# Generate Phase 12 DeBERTa numeric-feature ensemble submission
import gc
import shutil
import pandas as pd
import numpy as np
import torch
from pathlib import Path
from sklearn.metrics import f1_score
from torch.utils.data import DataLoader, SequentialSampler

label_names_map = {0: "Clear Reply", 1: "Ambivalent", 2: "Clear Non-Reply"}

def softmax_np(x, axis=-1):
    x = x - x.max(axis=axis, keepdims=True)
    e = np.exp(x)
    return e / e.sum(axis=axis, keepdims=True)

def load_run_logits_for_test(r):
    cfg = r["cfg"]
    run_dir = Path(r["run_dir"])
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    feature_stats = load_feature_stats(run_dir / "feature_stats.json")
    reload_model, reload_tok = load_feature_model_and_tokenizer(
        cfg.model_name,
        num_labels=NUM_LABELS,
        num_features=len(feature_stats["feature_names"]),
        feature_hidden=cfg.numeric_feature_hidden,
    )

    reload_model.load_state_dict(torch.load(run_dir / "best_model.pt", map_location=device))
    reload_model.to(device).eval()

    _, test_df = load_clarity()
    test_df_enc = test_df.copy()
    test_df_enc["label_id"] = 0
    test_df_enc = apply_text_transforms_for_config(test_df_enc, cfg)
    test_features = transform_numeric_features(test_df_enc, feature_stats)
    test_ds = tokenize_pairs_with_features(
        test_df_enc, reload_tok, cfg.max_length, cfg.input_fmt, test_features
    )
    test_loader = DataLoader(test_ds, batch_size=cfg.batch_size, sampler=SequentialSampler(test_ds))

    all_logits = []
    with torch.no_grad():
        for batch in test_loader:
            input_ids, attention_mask, _, features = [b.to(device) for b in batch]
            out = reload_model(input_ids=input_ids, attention_mask=attention_mask, features=features)
            all_logits.append(out.logits.cpu().numpy())
    test_logits = np.concatenate(all_logits, axis=0)

    reload_model.cpu()
    del reload_model, reload_tok
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return test_df, test_logits

def write_submission(name, test_df, preds):
    submission = pd.DataFrame({
        "Id": test_df["index"] if "index" in test_df.columns else range(len(test_df)),
        "Predicted": [label_names_map[int(p)] for p in preds],
    })
    path = f"/kaggle/working/{name}.csv"
    submission.to_csv(path, index=False)
    print(f"{name}.csv -> {path}")
    print(f"  Distribution: {dict(submission['Predicted'].value_counts())}")
    return path

# Important: keep this order. These are the Phase 12 submission weights:
# 0.9 * seed42 + 0.0 * seed0 + 0.1 * seed1.
run_by_seed = {r["cfg"].seed: r for r in sweep_results}
ordered_runs = [run_by_seed[42], run_by_seed[0], run_by_seed[1]]
phase12_weights = np.array([0.9, 0.0, 0.1], dtype=np.float32)

val_labels_ref = np.load(Path(ordered_runs[0]["run_dir"]) / "val_labels.npy")
val_probs = []
test_probs = []
test_df_ref = None

for r in ordered_runs:
    val_logits = np.load(Path(r["run_dir"]) / "val_preds.npy")
    val_probs.append(softmax_np(val_logits))
    test_df_ref, test_logits = load_run_logits_for_test(r)
    test_probs.append(softmax_np(test_logits))
    write_submission("submission_single_seed" + str(r["cfg"].seed), test_df_ref, test_logits.argmax(axis=1))

equal_val = np.mean(val_probs, axis=0)
equal_test = np.mean(test_probs, axis=0)
equal_f1 = f1_score(val_labels_ref, equal_val.argmax(axis=1), average="macro", zero_division=0)
write_submission("submission_equal_deberta_phase12", test_df_ref, equal_test.argmax(axis=1))
print(f"Equal ensemble val F1: {equal_f1:.4f}")

alpha_val = sum(w * p for w, p in zip(phase12_weights, val_probs))
alpha_test = sum(w * p for w, p in zip(phase12_weights, test_probs))
alpha_f1 = f1_score(val_labels_ref, alpha_val.argmax(axis=1), average="macro", zero_division=0)
alpha_path = write_submission("submission_alpha_deberta_phase12", test_df_ref, alpha_test.argmax(axis=1))
print(f"Phase 12 fixed-alpha val F1: {alpha_f1:.4f}, weights={phase12_weights.tolist()} for seeds [42, 0, 1]")

shutil.copyfile(alpha_path, "/kaggle/working/submission.csv")
print(f"Default /kaggle/working/submission.csv copied from: {alpha_path}")
`;

const downloadCell = (name) => `
# Optional: zip final model folders
import shutil
from pathlib import Path
from IPython.display import FileLink, display

tmp = Path("/kaggle/working/final_${name}_models")
tmp.mkdir(exist_ok=True)
for r in sweep_results:
    src = Path(r["run_dir"])
    if src.exists():
        shutil.copytree(src, tmp / src.name, dirs_exist_ok=True)

zip_base = "/kaggle/working/final_${name}_models"
shutil.make_archive(zip_base, "zip", str(tmp))
print(f"Created {zip_base}.zip")
display(FileLink("final_${name}_models.zip"))
`;

const notebooks = [
  {
    file: "kaggle_final_distilbert.ipynb",
    title: "Τελικό Notebook 1 - DistilBERT",
    summary: "Αυτό είναι το πρώτο από τα τρία τελικά notebooks της εργασίας και αφορά το DistilBERT. Το DistilBERT το αντιμετώπισα σαν το πιο ελαφρύ Transformer μοντέλο της τριάδας: αρκετά γρήγορο για δοκιμές, αλλά ακόμα βασισμένο στην ίδια λογική με το BERT. Δεν ήταν το μοντέλο που έδωσε το καλύτερο τελικό score, όμως ήταν πολύ χρήσιμο για να δω από νωρίς τι περίπου μπορεί να μάθει ένα pretrained μοντέλο στο CLARITY task.",
    notes: [
      "Best single DistilBERT: max_length=512, lr=3e-5, epochs=3, seed=42, weight_decay=0.0.",
      "Το πιο χρήσιμο συμπέρασμα από τα DistilBERT experiments ήταν ότι το μεγαλύτερο max_length βοηθάει, γιατί αρκετές απαντήσεις είναι μακριές και με μικρό context χάνεται πληροφορία.",
      "Το κρατάω απλό, χωρίς extra feature heads ή ensemble, ώστε να φαίνεται καθαρά τι κάνει το ίδιο το DistilBERT.",
    ],
    config: `
MODELS_DIR = "/kaggle/working/final_distilbert_models"
sweep_configs = [
    ExperimentConfig(
        model_name="distilbert-base-uncased",
        input_fmt="two_segment",
        max_length=512,
        lr=3e-5,
        batch_size=16,
        epochs=3,
        warmup_steps=100,
        weight_decay=0.0,
        mode="final",
        seed=42,
        models_dir=MODELS_DIR,
    ),
]
print("Queued:", sweep_configs[0].run_id)
`,
    submission: singleSubmissionCell("distilbert"),
    downloadName: "distilbert",
  },
  {
    file: "kaggle_final_bert.ipynb",
    title: "Τελικό Notebook 2 - BERT",
    summary: "Αυτό είναι το δεύτερο τελικό notebook και περιέχει το BERT run που ζητείται στην εργασία. Το BERT είναι το κλασικό μοντέλο αναφοράς για τέτοια NLP fine-tuning tasks, οπότε ήθελα να το τρέξω όσο πιο καθαρά γίνεται πριν πάω στο DeBERTa. Περίμενα ότι ίσως θα ξεπεράσει καθαρά το DistilBERT, αλλά τελικά η διαφορά ήταν μικρή.",
    notes: [
      "Best single BERT: lr=2e-5, epochs=5, max_length=256, seed=1, weight_decay=0.0.",
      "Το αποτέλεσμα ήταν κοντά στο DistilBERT και αρκετά πιο κάτω από το DeBERTa, άρα το απλό BERT δεν ήταν από μόνο του το breakthrough.",
      "Και εδώ κρατάω single-model setup, ώστε η σύγκριση DistilBERT / BERT / DeBERTa να είναι όσο γίνεται καθαρή.",
    ],
    config: `
MODELS_DIR = "/kaggle/working/final_bert_models"
sweep_configs = [
    ExperimentConfig(
        model_name="bert-base-uncased",
        input_fmt="two_segment",
        max_length=256,
        lr=2e-5,
        batch_size=16,
        epochs=5,
        warmup_steps=100,
        weight_decay=0.0,
        mode="final",
        seed=1,
        models_dir=MODELS_DIR,
    ),
]
print("Queued:", sweep_configs[0].run_id)
`,
    submission: singleSubmissionCell("bert"),
    downloadName: "bert",
  },
  {
    file: "kaggle_final_deberta.ipynb",
    title: "Τελικό Notebook 3 - DeBERTa-v3",
    summary: "Αυτό είναι το τρίτο και πιο σημαντικό τελικό notebook. Το DeBERTa ήταν το μοντέλο που τελικά δούλεψε καλύτερα στο CLARITY task. Εδώ κρατάω την εκδοχή που έδωσε το καλύτερο πραγματικό public Kaggle αποτέλεσμα: Phase 12 DeBERTa με numeric feature side-branch και fixed alpha ensemble τριών seeds.",
    notes: [
      "Αυτό είναι το setup που αντιστοιχεί στο public Kaggle 0.70, όχι το μεταγενέστερο Phase 18 local-validation ensemble.",
      "Το κείμενο μένει raw full Q/A. Τα extra signals μπαίνουν ως numeric features σε side branch, όχι ως tokens μέσα στο κείμενο.",
      "Το submission χρησιμοποιεί fixed weights 0.9 * seed42 + 0.0 * seed0 + 0.1 * seed1, όπως στο Phase 12 alpha ensemble.",
    ],
    config: `
MODELS_DIR = "/kaggle/working/final_deberta_phase12_models"
sweep_configs = [
    ExperimentConfig(
        model_name="microsoft/deberta-v3-base",
        input_fmt="two_segment",
        answer_view="full",
        max_length=256,
        lr=2e-5,
        batch_size=16,
        epochs=4,
        warmup_steps=100,
        weight_decay=0.0,
        mode="final",
        seed=42,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="base",
        use_surface_word_normalization=False,
    ),
    ExperimentConfig(
        model_name="microsoft/deberta-v3-base",
        input_fmt="two_segment",
        answer_view="full",
        max_length=256,
        lr=2e-5,
        batch_size=16,
        epochs=4,
        warmup_steps=100,
        weight_decay=0.0,
        mode="final",
        seed=0,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="base",
        use_surface_word_normalization=False,
    ),
    ExperimentConfig(
        model_name="microsoft/deberta-v3-base",
        input_fmt="two_segment",
        answer_view="full",
        max_length=256,
        lr=2e-5,
        batch_size=16,
        epochs=4,
        warmup_steps=100,
        weight_decay=0.0,
        mode="final",
        seed=1,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="base",
        use_surface_word_normalization=False,
    ),
]
print(f"Queued {len(sweep_configs)} DeBERTa Phase 12 numeric-feature runs")
for cfg in sweep_configs:
    print(" -", cfg.run_id)
`,
    submission: debertaPhase12SubmissionCell,
    downloadName: "deberta",
  },
  {
    file: "kaggle_final_deberta_large.ipynb",
    title: "Πειραματικό Notebook - DeBERTa-v3-large",
    summary: "Αυτό είναι ένα extra notebook για να δοκιμάσω την ιδέα που αναφέρω στο report ως future work: DeBERTa-v3-large αντί για DeBERTa-v3-base. Δεν το παρουσιάζω ως το official final model, γιατί δεν έχουμε ακόμα αποτελέσματα από Kaggle/validation για αυτό. Είναι όμως στημένο με την ίδια λογική του καλύτερου DeBERTa setup, ώστε να μπορεί να τρέξει σαν σοβαρό τελευταίο πείραμα.",
    notes: [
      "Model: microsoft/deberta-v3-large.",
      "Κρατάω το Phase 18 setup: numeric feature side-branch και ensemble από raw full, word-normalized full και focused answer view.",
      "Χρησιμοποιώ batch_size=2 γιατί το large μοντέλο είναι πολύ πιο βαρύ από το base και αλλιώς υπάρχει σοβαρός κίνδυνος OOM σε Kaggle GPU.",
      "Αν κάνει OOM ακόμα και έτσι, η πρώτη μείωση που θα έκανα είναι epochs/views, όχι max_length, γιατί το task χρειάζεται context.",
    ],
    config: `
MODELS_DIR = "/kaggle/working/final_deberta_large_phase18_models"
sweep_configs = [
    ExperimentConfig(
        model_name="microsoft/deberta-v3-large",
        input_fmt="two_segment",
        answer_view="full",
        max_length=256,
        lr=1e-5,
        batch_size=2,
        epochs=3,
        warmup_steps=100,
        weight_decay=0.0,
        mode="final",
        seed=42,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="base",
        use_surface_word_normalization=False,
    ),
    ExperimentConfig(
        model_name="microsoft/deberta-v3-large",
        input_fmt="two_segment",
        answer_view="full",
        max_length=256,
        lr=1e-5,
        batch_size=2,
        epochs=3,
        warmup_steps=100,
        weight_decay=0.0,
        mode="final",
        seed=42,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="base",
        use_surface_word_normalization=True,
    ),
    ExperimentConfig(
        model_name="microsoft/deberta-v3-large",
        input_fmt="two_segment",
        answer_view="focused",
        max_length=256,
        lr=1e-5,
        batch_size=2,
        epochs=3,
        warmup_steps=100,
        weight_decay=0.0,
        mode="final",
        seed=42,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="base",
        use_surface_word_normalization=False,
    ),
]
print(f"Queued {len(sweep_configs)} DeBERTa-v3-large Phase 18-style runs")
for cfg in sweep_configs:
    print(" -", cfg.run_id)
`,
    submission: debertaSubmissionCell,
    downloadName: "deberta_large",
  },
];

for (const spec of notebooks) {
  const cells = [
    md(`# ${spec.title}\n\n${spec.summary}\n\n` + spec.notes.map((n) => `- ${n}`).join("\n")),
    md("## 1. Εγκατάσταση dependencies\n\nΠρώτα εγκαθιστώ τις βιβλιοθήκες που χρειάζονται για το fine-tuning. Κρατάω συγκεκριμένη έκδοση του `transformers`, γιατί στα DeBERTa experiments είχα δει ότι μικρές αλλαγές στο setup μπορούν να αλλάξουν τελείως τη συμπεριφορά του μοντέλου. Αν το Kaggle ζητήσει restart μετά την εγκατάσταση, κάνω restart και συνεχίζω από το επόμενο cell."),
    code(installCell),
    md("## 2. Βοηθητικές συναρτήσεις\n\nΣε αυτό το κομμάτι ορίζονται οι συναρτήσεις που χρησιμοποιούνται παρακάτω: φόρτωση δεδομένων, preprocessing, tokenization, training loop, evaluation και submission generation. Είναι μεγάλο cell, αλλά πρακτικά είναι απλώς το τεχνικό υπόβαθρο για να μπορέσουν τα επόμενα cells να μείνουν καθαρά."),
    code(libraryCell),
    md("## 3. Τελικό configuration\n\nΕδώ ορίζω το τελικό run για αυτό το μοντέλο. Τα hyperparameters είναι αυτά που κράτησα μετά τα πειράματα: learning rate, max length, epochs, seed και weight decay. Δεν είναι όλες οι δυνατές δοκιμές εδώ, μόνο η τελική επιλογή."),
    code(spec.config),
    md("## 4. Training\n\nΕδώ γίνεται το fine-tuning. Ξεκινάω από ένα pretrained μοντέλο που ήδη έχει μάθει αρκετή γλώσσα και το εκπαιδεύω πάνω στις τρεις κλάσεις του CLARITY: `Clear Reply`, `Ambivalent`, και `Clear Non-Reply`. Κρατάω το καλύτερο checkpoint με βάση το validation macro-F1, γιατί το τελευταίο epoch δεν είναι πάντα το καλύτερο."),
    code(runSweepCell),
    md("## 5. Validation results\n\nΕδώ κοιτάω το αποτέλεσμα στο validation set. Το accuracy είναι χρήσιμο, αλλά το βασικό metric είναι το macro-F1, επειδή δίνει ίσο βάρος και στις τρεις κλάσεις. Αυτό έχει σημασία γιατί η `Ambivalent` είναι πολύ συχνή και ένα μοντέλο μπορεί να φαίνεται καλό ενώ στην πραγματικότητα αγνοεί τις πιο δύσκολες κλάσεις."),
    code(resultsCell),
    md("## 6. Confusion matrix\n\nΤο confusion matrix δείχνει όχι μόνο πόσα λάθη κάνει το μοντέλο, αλλά και τι είδους λάθη κάνει. Στο συγκεκριμένο task με ενδιαφέρει πολύ αν το μοντέλο σπρώχνει τα πάντα προς `Ambivalent`, γιατί αυτό ήταν συχνό failure mode στα πειράματα."),
    code(confusionCell),
    md("## 7. Kaggle submission\n\nΤέλος, παράγω το αρχείο για υποβολή στο Kaggle. Το αρχείο που ανεβάζω είναι το `/kaggle/working/submission.csv` και έχει τις δύο στήλες που ζητάει ο διαγωνισμός: `Id` και `Predicted`. Εκτυπώνω και την κατανομή των προβλέψεων, γιατί αν δω π.χ. σχεδόν όλα `Ambivalent`, ξέρω αμέσως ότι κάτι πήγε στραβά."),
    code(spec.submission),
    md("## 8. Προαιρετικό zip με artifacts\n\nΑυτό το τελευταίο cell δεν είναι απαραίτητο για το submission. Το χρησιμοποιώ μόνο αν θέλω να κρατήσω τα checkpoints και τα validation predictions από το run, ώστε να μπορώ αργότερα να ξαναδώ τα αποτελέσματα χωρίς να ξανατρέξω όλο το training."),
    code(downloadCell(spec.downloadName)),
  ];
  const nb = {
    cells,
    metadata: {
      kernelspec: { display_name: "Python 3", language: "python", name: "python3" },
      language_info: { name: "python", version: "3.12" },
    },
    nbformat: 4,
    nbformat_minor: 5,
  };
  const outPath = path.join(outDir, spec.file);
  fs.writeFileSync(outPath, JSON.stringify(nb, null, 1));
  console.log(`Built ${outPath} (${cells.length} cells)`);
}
