const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const srcDir = path.join(root, "src");
const nbPath = path.join(root, "notebooks", "kaggle_experiment.ipynb");

const filesInOrder = [
  "config.py",
  "data.py",
  "features.py",
  "evasion_stack.py",
  "tokenization.py",
  "model.py",
  "features_head.py",
  "multitask.py",
  "train.py",
  "evaluate.py",
  "experiment.py",
];

function stripIntraImports(text) {
  return text
    .replace(/^from \.[\w_]+ import \([^)]*\)/gm, "")
    .replace(/^from \.[\w_]+ import .+$/gm, "")
    .replace(/^from \. import .+$/gm, "");
}

function lines(text) {
  const arr = text.split(/\r?\n/);
  return arr.map((line, i) => (i < arr.length - 1 ? line + "\n" : line));
}

function buildLibraryCell() {
  const parts = [
    "# Cell 2 - Library (inlined src/) - auto-generated by scripts/prepare_breakthrough_notebook.js",
    "# " + "=".repeat(60),
  ];
  for (const fname of filesInOrder) {
    const full = path.join(srcDir, fname);
    parts.push("# " + "=".repeat(60));
    parts.push(`# src/${fname}`);
    parts.push("# " + "=".repeat(60));
    parts.push(stripIntraImports(fs.readFileSync(full, "utf8")).trimEnd() + "\n");
  }
  parts.push('print("library loaded ok")');
  return parts.join("\n");
}

const intro = `# AI2 HW2 - Phase 19: full-context help + dual-view model

**If you see this, you have the correct notebook version.**

This sweep keeps full context and adds help, instead of replacing the answer.

It tests:
- full raw answer + long_mixed numeric features
- full word-normalized answer + long_mixed numeric features
- simple multi-view ensemble member: focused answer + long_mixed numeric features
- heavier architecture: one model runs DeBERTa on full Q/A and focused Q/A, then combines both vectors with features

The dual-view model is expensive, so it uses batch_size=8.

Queued experiments:
1. raw full answer + long_mixed numeric features
2. wordnorm full answer + long_mixed numeric features
3. focused answer + long_mixed numeric features
4. dual-view full+focused + long_mixed numeric features
5. dual-view wordnorm full+focused + long_mixed numeric features

The submission cell saves:
- one submission per run
- equal/alpha ensemble files
- default submission.csv in Kaggle format: Id,Predicted`;

const cell3 = `# Cell 3 - Phase 19: full-context help + dual-view model

MODELS_DIR = "/kaggle/working/models_phase19_dualview"

sweep_configs = [
    ExperimentConfig(
        model_name="microsoft/deberta-v3-base",
        input_fmt="two_segment",
        answer_view="full",
        max_length=256,
        lr=2e-5,
        batch_size=16,
        epochs=4,
        warmup_steps=100,
        weight_decay=0.0,
        mode="dev",
        seed=42,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="long_mixed",
        use_surface_word_normalization=False,
        use_evidence_word_prefix=False,
    ),
    ExperimentConfig(
        model_name="microsoft/deberta-v3-base",
        input_fmt="two_segment",
        answer_view="full",
        max_length=256,
        lr=2e-5,
        batch_size=16,
        epochs=4,
        warmup_steps=100,
        weight_decay=0.0,
        mode="dev",
        seed=42,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="long_mixed",
        use_surface_word_normalization=True,
        use_evidence_word_prefix=False,
    ),
    ExperimentConfig(
        model_name="microsoft/deberta-v3-base",
        input_fmt="two_segment",
        answer_view="focused",
        max_length=256,
        lr=2e-5,
        batch_size=16,
        epochs=4,
        warmup_steps=100,
        weight_decay=0.0,
        mode="dev",
        seed=42,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="long_mixed",
        use_surface_word_normalization=False,
        use_evidence_word_prefix=False,
    ),
    ExperimentConfig(
        model_name="microsoft/deberta-v3-base",
        input_fmt="two_segment",
        answer_view="full",
        max_length=256,
        lr=2e-5,
        batch_size=8,
        epochs=4,
        warmup_steps=100,
        weight_decay=0.0,
        mode="dev",
        seed=42,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        use_dual_view=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="long_mixed",
        use_surface_word_normalization=False,
        use_evidence_word_prefix=False,
    ),
    ExperimentConfig(
        model_name="microsoft/deberta-v3-base",
        input_fmt="two_segment",
        answer_view="full",
        max_length=256,
        lr=2e-5,
        batch_size=8,
        epochs=4,
        warmup_steps=100,
        weight_decay=0.0,
        mode="dev",
        seed=42,
        models_dir=MODELS_DIR,
        use_numeric_features=True,
        use_dual_view=True,
        numeric_feature_hidden=64,
        numeric_feature_profile="long_mixed",
        use_surface_word_normalization=True,
        use_evidence_word_prefix=False,
    ),
]

print(f"{len(sweep_configs)} run(s) queued:")
for cfg in sweep_configs:
    print(" -", cfg.run_id)

print("\\nPass bar:")
print(" - Strong pass: val_f1_macro > 0.7070 (beats current local alpha ensemble)")
print(" - Useful pass: val_f1_macro > 0.7007 (beats Phase 12 seed42 numfeat)")
print(" - If these fail, stop experiments and write the report around Phase 18/17/12.")`;

const cell7 = `# Cell 7 - Generate single-seed and ensemble submission CSVs
import gc
import shutil
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.metrics import f1_score

label_names_map = {0: "Clear Reply", 1: "Ambivalent", 2: "Clear Non-Reply"}

def softmax_np(x, axis=-1):
    x = x - x.max(axis=axis, keepdims=True)
    e = np.exp(x)
    return e / e.sum(axis=axis, keepdims=True)

def load_run_logits_for_test(r):
    cfg = r["cfg"]
    run_dir = Path(r["run_dir"])
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    if cfg.use_dual_view:
        feature_stats = load_feature_stats(run_dir / "feature_stats.json")
        evasion_stack_model = None
        reload_model, reload_tok = load_dual_view_feature_model_and_tokenizer(
            cfg.model_name,
            num_labels=NUM_LABELS,
            num_features=len(feature_stats["feature_names"]),
            feature_hidden=cfg.numeric_feature_hidden,
        )
    elif cfg.use_numeric_features:
        feature_stats = load_feature_stats(run_dir / "feature_stats.json")
        evasion_stack_model = (
            load_evasion_stack_model(run_dir / "evasion_stack.joblib")
            if cfg.use_evasion_proba_features else None
        )
        reload_model, reload_tok = load_feature_model_and_tokenizer(
            cfg.model_name,
            num_labels=NUM_LABELS,
            num_features=len(feature_stats["feature_names"]),
            feature_hidden=cfg.numeric_feature_hidden,
        )
    else:
        feature_stats = None
        evasion_stack_model = None
        reload_model, reload_tok = load_model_and_tokenizer(cfg.model_name, num_labels=NUM_LABELS)

    extra_tokens = special_tokens_for_config(cfg)
    if extra_tokens:
        added = ensure_special_tokens(extra_tokens, reload_tok, reload_model)
        print(f"[reload] re-added {added} special tokens before loading checkpoint")
    reload_model.load_state_dict(torch.load(run_dir / "best_model.pt", map_location=device))
    reload_model.to(device)
    reload_model.eval()

    _, test_df = load_clarity()
    test_df_enc = test_df.copy()
    test_df_enc["label_id"] = 0
    test_df_enc = apply_text_transforms_for_config(test_df_enc, cfg)

    if cfg.use_dual_view:
        test_features = transform_numeric_features(test_df_enc, feature_stats)
        test_df_second = test_df.copy()
        test_df_second["label_id"] = 0
        test_df_second = apply_text_transforms_for_config(test_df_second, cfg, answer_view="focused")
        test_ds = tokenize_dual_view_pairs_with_features(
            test_df_enc,
            test_df_second,
            reload_tok,
            cfg.max_length,
            cfg.input_fmt,
            test_features,
        )
    elif cfg.use_numeric_features:
        test_features = transform_numeric_features(test_df_enc, feature_stats)
        if cfg.use_evasion_proba_features:
            evasion_probs = transform_evasion_stack_features(test_df_enc, evasion_stack_model)
            test_features = np.concatenate([test_features, evasion_probs], axis=1)
        test_ds = tokenize_pairs_with_features(
            test_df_enc, reload_tok, cfg.max_length, cfg.input_fmt, test_features
        )
    else:
        test_ds = tokenize_pairs(test_df_enc, reload_tok, cfg.max_length, cfg.input_fmt)
    test_loader = DataLoader(test_ds, batch_size=cfg.batch_size, sampler=SequentialSampler(test_ds))

    all_logits = []
    with torch.no_grad():
        for batch in test_loader:
            batch = [b.to(device) for b in batch]
            if len(batch) == 6:
                input_ids, attention_mask, input_ids_2, attention_mask_2, labels, features = batch
                out = reload_model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    input_ids_2=input_ids_2,
                    attention_mask_2=attention_mask_2,
                    features=features,
                )
            else:
                input_ids, attention_mask, labels = batch[:3]
            if len(batch) == 4:
                out = reload_model(input_ids=input_ids, attention_mask=attention_mask, features=batch[3])
            elif len(batch) != 6:
                out = reload_model(input_ids=input_ids, attention_mask=attention_mask)
            all_logits.append(out.logits.cpu().numpy())
    test_logits = np.concatenate(all_logits, axis=0)

    reload_model.cpu()
    del reload_model, reload_tok
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return test_df, test_logits

def write_submission(name, test_df, preds):
    submission = pd.DataFrame({
        "Id": test_df["index"] if "index" in test_df.columns else range(len(test_df)),
        "Predicted": [label_names_map[int(p)] for p in preds],
    })
    path = f"/kaggle/working/{name}.csv"
    submission.to_csv(path, index=False)
    print(f"{name}.csv -> {path}")
    print(f"  Distribution: {dict(submission['Predicted'].value_counts())}")
    return path

all_runs = sorted(sweep_results, key=lambda r: r["val_f1_macro"], reverse=True)
val_labels_ref = np.load(Path(all_runs[0]["run_dir"]) / "val_labels.npy")

test_df_ref = None
val_probs = []
test_probs = []
for r in all_runs:
    val_logits = np.load(Path(r["run_dir"]) / "val_preds.npy")
    val_probs.append(softmax_np(val_logits))
    test_df_ref, test_logits = load_run_logits_for_test(r)
    test_probs.append(softmax_np(test_logits))
    safe_id = r["run_id"].replace("/", "_")
    write_submission(f"submission_single_{safe_id}", test_df_ref, test_logits.argmax(axis=1))

best_single = all_runs[0]
print(f"Best single: {best_single['run_id']} val={best_single['val_f1_macro']:.4f}")

equal_val = np.mean(val_probs, axis=0)
equal_test = np.mean(test_probs, axis=0)
equal_f1 = f1_score(val_labels_ref, equal_val.argmax(axis=1), average="macro", zero_division=0)
equal_path = write_submission("submission_equal_phase19_dualview", test_df_ref, equal_test.argmax(axis=1))
print(f"Equal ensemble val F1: {equal_f1:.4f}")

grid = np.linspace(0.0, 1.0, 21)
best = (-1.0, None)
if len(val_probs) == 1:
    best = (all_runs[0]["val_f1_macro"], np.array([1.0], dtype=np.float32))
elif len(val_probs) == 2:
    for a in grid:
        weights = np.array([a, 1.0 - a], dtype=np.float32)
        ens = sum(w * p for w, p in zip(weights, val_probs))
        f1 = f1_score(val_labels_ref, ens.argmax(axis=1), average="macro", zero_division=0)
        if f1 > best[0]:
            best = (f1, weights)
else:
    for a in grid:
        for b in grid:
            c = 1.0 - a - b
            if c < -1e-9:
                continue
            weights = np.array([a, b, c], dtype=np.float32)
            ens = sum(w * p for w, p in zip(weights, val_probs))
            f1 = f1_score(val_labels_ref, ens.argmax(axis=1), average="macro", zero_division=0)
            if f1 > best[0]:
                best = (f1, weights)

best_f1, best_w = best
alpha_test = sum(w * p for w, p in zip(best_w, test_probs))
alpha_path = write_submission("submission_alpha_phase19_dualview", test_df_ref, alpha_test.argmax(axis=1))
print(f"Alpha ensemble val F1: {best_f1:.4f}, weights={best_w.tolist()}")

chosen = alpha_path if best_f1 >= equal_f1 else equal_path
shutil.copyfile(chosen, "/kaggle/working/submission.csv")
print(f"Default /kaggle/working/submission.csv copied from: {chosen}")`;

const errorAnalysisCell = `# Cell 6b - Validation error analysis for preprocessing decisions
import re
import pandas as pd
import numpy as np
from pathlib import Path

label_names_map = {0: "Clear Reply", 1: "Ambivalent", 2: "Clear Non-Reply"}

def has_any(text, patterns):
    text = str(text).lower()
    return int(any(re.search(p, text) for p in patterns))

def add_error_patterns(df):
    out = df.copy()
    q = out["question_orig"].astype(str).str.lower()
    a = out["answer_orig"].astype(str).str.lower()
    a_open = a.str.split().str[:14].str.join(" ")

    out["p_answer_has_year"] = a.str.contains(r"\\b(?:18|19|20)\\d{2}\\b", regex=True).astype(int)
    out["p_answer_has_money"] = a.str.contains(r"[$€£]|\\b(dollars?|euros?|pounds?|usd|eur|gbp|million|billion|trillion)\\b", regex=True).astype(int)
    out["p_answer_has_percent"] = a.str.contains(r"\\b\\d+(?:\\.\\d+)?\\s?(?:%|percent)\\b", regex=True).astype(int)
    out["p_answer_has_number"] = a.str.contains(r"\\b\\d+(?:[,.]\\d+)*(?:\\.\\d+)?\\b", regex=True).astype(int)
    out["p_answer_has_causal"] = a.str.contains(r"\\b(because|therefore|as a result|reason)\\b", regex=True).astype(int)
    out["p_answer_has_uncertain"] = a.str.contains(r"\\b(maybe|perhaps|probably|possibly|i think|i believe|it depends|not sure)\\b", regex=True).astype(int)
    out["p_answer_has_nonreply"] = a.str.contains(r"\\b(no comment|not going to answer|can't answer|cannot answer|do not know|don't know|decline to)\\b", regex=True).astype(int)
    out["p_answer_opens_yesno"] = a_open.str.contains(r"^(yes|yeah|absolutely|certainly|sure|no|not really|never)\\b", regex=True).astype(int)
    out["p_answer_opens_deflect"] = a_open.str.contains(r"^(well|look|let me|first of all)\\b", regex=True).astype(int)
    out["p_multi_question"] = out.get("multiple_questions", pd.Series(False, index=out.index)).fillna(False).astype(int)
    out["p_affirmative_question"] = out.get("affirmative_questions", pd.Series(False, index=out.index)).fillna(False).astype(int)
    out["p_long_answer"] = (out["answer_orig"].astype(str).str.split().str.len() >= 180).astype(int)
    out["p_short_answer"] = (out["answer_orig"].astype(str).str.split().str.len() <= 35).astype(int)
    return out

def rebuild_validation_frame(cfg):
    train_df, _ = load_clarity()
    cleaned = encode_labels(clean_data(train_df))
    train_idx, val_idx = create_split(cleaned, val_size=0.1, seed=cfg.split_id)
    val_orig = cleaned.iloc[val_idx].reset_index(drop=True).copy()
    val_trans = apply_text_transforms_for_config(val_orig, cfg)
    out = val_orig.copy()
    out["question_orig"] = val_orig["question"].astype(str)
    out["answer_orig"] = val_orig["answer"].astype(str)
    out["question_model"] = val_trans["question"].astype(str)
    out["answer_model"] = val_trans["answer"].astype(str)
    return out

pattern_cols = [
    "p_answer_has_year", "p_answer_has_money", "p_answer_has_percent", "p_answer_has_number",
    "p_answer_has_causal", "p_answer_has_uncertain", "p_answer_has_nonreply",
    "p_answer_opens_yesno", "p_answer_opens_deflect", "p_multi_question",
    "p_affirmative_question", "p_long_answer", "p_short_answer",
]

for r in sorted(sweep_results, key=lambda x: x["val_f1_macro"], reverse=True):
    cfg = r["cfg"]
    run_dir = Path(r["run_dir"])
    val_logits = np.load(run_dir / "val_preds.npy")
    val_labels = np.load(run_dir / "val_labels.npy")
    preds = val_logits.argmax(axis=1)

    err = rebuild_validation_frame(cfg)
    err["gold_id"] = val_labels
    err["pred_id"] = preds
    err["gold"] = [label_names_map[int(x)] for x in val_labels]
    err["pred"] = [label_names_map[int(x)] for x in preds]
    err["correct"] = err["gold_id"] == err["pred_id"]
    err["confidence"] = softmax_np(val_logits).max(axis=1)
    err = add_error_patterns(err)
    wrong = err[~err["correct"]].copy()

    print("\\n" + "=" * 90)
    print(r["run_id"])
    print(f"val_f1_macro={r['val_f1_macro']:.4f}  wrong={len(wrong)}/{len(err)}")
    print("\\nConfusions:")
    display(pd.crosstab(err["gold"], err["pred"], rownames=["gold"], colnames=["pred"]))

    print("\\nPattern rate in wrong vs correct validation rows:")
    summary = pd.DataFrame({
        "wrong_rate": wrong[pattern_cols].mean(),
        "correct_rate": err[err["correct"]][pattern_cols].mean(),
    })
    summary["gap_wrong_minus_correct"] = summary["wrong_rate"] - summary["correct_rate"]
    display(summary.sort_values("gap_wrong_minus_correct", ascending=False).round(3))

    print("\\nMost confident wrong examples:")
    cols = [
        "index", "gold", "pred", "confidence",
        "question_orig", "answer_orig", "question_model", "answer_model",
    ]
    display(
        wrong.sort_values("confidence", ascending=False)[cols]
        .head(12)
        .style.set_properties(subset=["question_orig", "answer_orig", "question_model", "answer_model"], **{"white-space": "pre-wrap"})
    )

    print("\\nWrong examples by confusion type:")
    for (gold, pred), grp in wrong.groupby(["gold", "pred"]):
        print(f"\\n--- {gold} -> {pred}: {len(grp)} rows ---")
        display(
            grp.sort_values("confidence", ascending=False)[cols]
            .head(5)
            .style.set_properties(subset=["question_orig", "answer_orig", "question_model", "answer_model"], **{"white-space": "pre-wrap"})
        )`;

const calibrationCell = `# Cell 7b - Optional class-multiplier calibration for current ensemble
# This does not retrain. It searches class multipliers on validation probabilities
# and applies the best multipliers to the already-computed alpha test probabilities.
from sklearn.metrics import f1_score
import numpy as np
import pandas as pd
import shutil

if "best_w" not in globals() or "val_probs" not in globals() or "test_probs" not in globals():
    raise RuntimeError("Run Cell 7 first so alpha ensemble probabilities exist.")

alpha_val = sum(w * p for w, p in zip(best_w, val_probs))
alpha_test = sum(w * p for w, p in zip(best_w, test_probs))
base_alpha_f1 = f1_score(val_labels_ref, alpha_val.argmax(axis=1), average="macro", zero_division=0)

grid = np.arange(0.70, 1.31, 0.05)
best_cal = (base_alpha_f1, np.array([1.0, 1.0, 1.0], dtype=np.float32))
for cr in grid:
    for amb in grid:
        for cnr in grid:
            mult = np.array([cr, amb, cnr], dtype=np.float32)
            pred = (alpha_val * mult).argmax(axis=1)
            f1 = f1_score(val_labels_ref, pred, average="macro", zero_division=0)
            if f1 > best_cal[0]:
                best_cal = (f1, mult)

cal_f1, cal_mult = best_cal
cal_test_pred = (alpha_test * cal_mult).argmax(axis=1)
cal_path = write_submission("submission_alpha_phase19_dualview_calibrated", test_df_ref, cal_test_pred)

print(f"Base alpha val F1:       {base_alpha_f1:.4f}")
print(f"Calibrated alpha val F1: {cal_f1:.4f}")
print(f"Class multipliers [CR, AMB, CNR]: {cal_mult.tolist()}")
print(f"Calibrated CSV: {cal_path}")

if cal_f1 >= base_alpha_f1:
    shutil.copyfile(cal_path, "/kaggle/working/submission_calibrated.csv")
    print("Copied calibrated file to /kaggle/working/submission_calibrated.csv")
else:
    print("Calibration did not improve validation; keep /kaggle/working/submission.csv")`;

const nb = JSON.parse(fs.readFileSync(nbPath, "utf8"));
nb.cells[0].source = lines(intro);
nb.cells[2].source = lines(buildLibraryCell());
nb.cells[2].outputs = [];
nb.cells[2].execution_count = null;
nb.cells[3].source = lines(cell3);
nb.cells[3].outputs = [];
nb.cells[3].execution_count = null;
const errorCell = {
  cell_type: "code",
  execution_count: null,
  metadata: {},
  outputs: [],
  source: lines(errorAnalysisCell),
};
const existingErrorIdx = nb.cells.findIndex((cell) => {
  const src = Array.isArray(cell.source) ? cell.source.join("") : (cell.source || "");
  return src.startsWith("# Cell 6b - Validation error analysis");
});
if (existingErrorIdx >= 0) {
  nb.cells[existingErrorIdx] = errorCell;
} else {
  nb.cells.splice(8, 0, errorCell);
}
const submissionIdx = nb.cells.findIndex((cell) => {
  const src = Array.isArray(cell.source) ? cell.source.join("") : (cell.source || "");
  return src.startsWith("# Cell 7 - Generate single-seed");
});
if (submissionIdx >= 0) {
  nb.cells[submissionIdx].source = lines(cell7);
  nb.cells[submissionIdx].outputs = [];
  nb.cells[submissionIdx].execution_count = null;
}
const calCell = {
  cell_type: "code",
  execution_count: null,
  metadata: {},
  outputs: [],
  source: lines(calibrationCell),
};
const existingCalIdx = nb.cells.findIndex((cell) => {
  const src = Array.isArray(cell.source) ? cell.source.join("") : (cell.source || "");
  return src.startsWith("# Cell 7b - Optional class-multiplier calibration");
});
if (existingCalIdx >= 0) {
  nb.cells[existingCalIdx] = calCell;
} else if (submissionIdx >= 0) {
  nb.cells.splice(submissionIdx + 1, 0, calCell);
}

fs.writeFileSync(nbPath, JSON.stringify(nb, null, 1));
console.log("Prepared notebooks/kaggle_experiment.ipynb for Phase 19 dual-view run.");
